/**
 * Founder OS — scaffolding templates
 *
 * String templates used by `founderos init`. Kept as plain functions so
 * they're trivially testable and don't need a templating dependency.
 */

export interface ProjectConfig {
  version: 1;
  tools: string[];
  skills: string[];
  createdAt: string;
}

export function renderProjectReadme(config: ProjectConfig): string {
  return `# Founder OS — project setup

This project has Founder OS skills installed locally so the whole team shares
the same AI workflows.

## What's here

- **Tools configured:** ${config.tools.join(', ') || 'none'}
- **Skills installed:** ${config.skills.length}
- **Config:** \`.founderos.json\` (commit this)

## Skills

${config.skills.map((s) => `- \`/${s}\``).join('\n')}

## For teammates

After cloning, run:

\`\`\`bash
npx founderos init
\`\`\`

This re-places the skills into your local tool directories using the pinned
config. No global install required.

## Updating

\`\`\`bash
npx founderos update
\`\`\`

---
Generated by Founder OS · https://founderos.dev
`;
}

export function renderSkillStub(id: string): string {
  return `---
name: ${id}
description: One sentence — what this skill does and when to trigger it.
version: 0.1.0
category: strategy
tools: [Claude Code, Cursor, Codex CLI, Gemini CLI]
---

# ${id}

## Purpose

## Use Cases

## Ideal User

## Input Requirements

## Operating Principles

## Workflow Engine

## Output Schema

## Quality Checklist

## Examples

## Anti-Patterns

## Advanced Mode

## Best Practices

## Integration Compatibility
`;
}
